In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv
import seaborn as sns

In [2]:
mcu= pd.read_csv('csv_files/marvel_box_office.csv')

In [3]:
mcu

,Movie,Release Date,Release Month,Release Day,Release Year,Ownership,Domestic Box Office,Inflation Adjusted Domestic,International Box Office,Inflation Adjusted International,...,Inflation Adjusted Opening Weekend,Budget,Inflation Adjusted Budget,IMDb Score,Meta Score,Tomatometer,Rotten Tomato Audience Score,Run Time In Minutes,Phase,Director
0,Iron Man,5/2/2008,May,2,2008,Marvel Studios,318604126,467231126,266567421,390919596,...,149756442,186000000,272767935,7.9,79,94,91,126,One,Jon Favreau
1,The Incredible Hulk,6/13/2008,June,13,2008,Marvel Studios,134806913,197704288,130766946,191779378,...,81268794,137500000,201653899,6.6,61,67,69,112,One,Louis Leterrier
2,Iron Man 2,5/7/2010,May,7,2010,Marvel Studios,312433331,416973763,308723058,412022030,...,170992360,170000000,226882130,6.9,57,72,71,124,One,Jon Favreau
3,Thor,5/6/2011,May,6,2011,Marvel Studios,181030624,240384926,268295994,356261892,...,87271973,150000000,199180327,7.0,57,77,76,115,One,Kenneth Brangh
4,Captain America: The First Avenger,7/22/2011,July,22,2011,Marvel Studios,176654505,234574020,193915271,257494054,...,86389190,140000000,185901643,6.9,66,80,75,124,One,Joe Johnston
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Blade II,3/22/2002,March,22,2002,New Line Cinema,81676888,148030572,72661713,131691537,...,58953529,54000000,97869190,6.7,52,57,68,117,NaN,Guillermo del Toro
64,Blade: Trinity,12/8/2004,December,8,2004,New Line Cinema,52397389,88619322,78955776,133537328,...,27164311,65000000,109934026,5.8,38,24,58,113,NaN,David S. Goyer
65,Morbius,4/1/2022,April,1,2022,Sony Pictures,73865530,73865530,88893907,88893907,...,39005895,75000000,75000000,5.2,35,15,71,104,NaN,Daniel Espinosa
66,Hulk,6/20/2003,June,20,2003,Universal Pictures,132177234,230816958,112854445,197074178,...,108492911,137000000,239238803,5.6,54,63,29,138,NaN,Ang Lee
67,Madame Web,2/12/2024,February,12,2024,Sony Pictures,43756623,43756623,53941282,53941282,...,15335860,80000000,80000000,3.8,26,12,57,116,NaN,S.J. Clarkson

In [5]:
mcu.dtypes

Movie                                  object
Release Date                           object
Release Month                          object
Release Day                             int64
Release Year                            int64
Ownership                              object
Domestic Box Office                     int64
Inflation Adjusted Domestic             int64
International Box Office                int64
Inflation Adjusted International        int64
Worldwide Box Office                    int64
Inflation Adjusted Worldwide            int64
Opening Weekend                         int64
Inflation Adjusted Opening Weekend      int64
Budget                                  int64
Inflation Adjusted Budget               int64
IMDb Score                            float64
Meta Score                              int64
Tomatometer                             int64
Rotten Tomato Audience Score            int64
Run Time In Minutes                     int64
Phase                                  object
Director                               object
dtype: object

In [6]:
mcu.columns

Index(['Movie', 'Release Date', 'Release Month', 'Release Day', 'Release Year',
       'Ownership', 'Domestic Box Office', 'Inflation Adjusted Domestic',
       'International Box Office', 'Inflation Adjusted International',
       'Worldwide Box Office', 'Inflation Adjusted Worldwide',
       'Opening Weekend', 'Inflation Adjusted Opening Weekend', 'Budget',
       'Inflation Adjusted Budget', 'IMDb Score', 'Meta Score', 'Tomatometer',
       'Rotten Tomato Audience Score', 'Run Time In Minutes', 'Phase',
       'Director'],
      dtype='object')

In [7]:



mcu_data=pd.DataFrame({
    "Movie":mcu["Movie"],
    "Release Year": mcu["Release Year"], 
    "Ownership" : mcu["Ownership"],
    "Director" : mcu["Director"],
    "Run Time(minutes)" : mcu["Run Time In Minutes"],
    "Phase" : mcu["Phase"],
    "Total Box Office(inflation)": mcu["Inflation Adjusted Worldwide"],
    "Opening weekend" : mcu["Inflation Adjusted Opening Weekend"],
    "Imdb rating": mcu["IMDb Score"],
    "Tomatometer": mcu["Tomatometer"],
    "Rotten Tomato (audience)": mcu["Rotten Tomato Audience Score"]
})

In [8]:
mcu_data.dtypes

Movie                           object
Release Year                     int64
Ownership                       object
Director                        object
Run Time(minutes)                int64
Phase                           object
Total Box Office(inflation)      int64
Opening weekend                  int64
Imdb rating                    float64
Tomatometer                      int64
Rotten Tomato (audience)         int64
dtype: object

In [9]:
mcu_data

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
0,Iron Man,2008,Marvel Studios,Jon Favreau,126,One,858150722,149756442,7.9,94,91
1,The Incredible Hulk,2008,Marvel Studios,Louis Leterrier,112,One,389483666,81268794,6.6,67,69
2,Iron Man 2,2010,Marvel Studios,Jon Favreau,124,One,828995793,170992360,6.9,72,71
3,Thor,2011,Marvel Studios,Kenneth Brangh,115,One,596646818,87271973,7.0,77,76
4,Captain America: The First Avenger,2011,Marvel Studios,Joe Johnston,124,One,492068074,86389190,6.9,80,75
...,...,...,...,...,...,...,...,...,...,...,...
63,Blade II,2002,New Line Cinema,Guillermo del Toro,117,NaN,279722109,58953529,6.7,57,68
64,Blade: Trinity,2004,New Line Cinema,David S. Goyer,113,NaN,222156650,27164311,5.8,24,58
65,Morbius,2022,Sony Pictures,Daniel Espinosa,104,NaN,162759437,39005895,5.2,15,71
66,Hulk,2003,Universal Pictures,Ang Lee,138,NaN,427891136,108492911,5.6,63,29
67,Madame Web,2024,Sony Pictures,S.J. Clarkson,116,NaN,97697905,15335860,3.8,12,57

In [10]:
mcu_data

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
0,Iron Man,2008,Marvel Studios,Jon Favreau,126,One,858150722,149756442,7.9,94,91
1,The Incredible Hulk,2008,Marvel Studios,Louis Leterrier,112,One,389483666,81268794,6.6,67,69
2,Iron Man 2,2010,Marvel Studios,Jon Favreau,124,One,828995793,170992360,6.9,72,71
3,Thor,2011,Marvel Studios,Kenneth Brangh,115,One,596646818,87271973,7.0,77,76
4,Captain America: The First Avenger,2011,Marvel Studios,Joe Johnston,124,One,492068074,86389190,6.9,80,75
...,...,...,...,...,...,...,...,...,...,...,...
63,Blade II,2002,New Line Cinema,Guillermo del Toro,117,NaN,279722109,58953529,6.7,57,68
64,Blade: Trinity,2004,New Line Cinema,David S. Goyer,113,NaN,222156650,27164311,5.8,24,58
65,Morbius,2022,Sony Pictures,Daniel Espinosa,104,NaN,162759437,39005895,5.2,15,71
66,Hulk,2003,Universal Pictures,Ang Lee,138,NaN,427891136,108492911,5.6,63,29
67,Madame Web,2024,Sony Pictures,S.J. Clarkson,116,NaN,97697905,15335860,3.8,12,57

In [11]:
print(mcu["Inflation Adjusted Worldwide"].dtype)
print(mcu["Inflation Adjusted Domestic"].dtype)

int64
int64

In [12]:
mcu_movies=mcu_data.loc[mcu_data['Ownership']== 'Marvel Studios']

In [13]:
mcu_movies

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
0,Iron Man,2008,Marvel Studios,Jon Favreau,126,One,858150722,149756442,7.9,94,91
1,The Incredible Hulk,2008,Marvel Studios,Louis Leterrier,112,One,389483666,81268794,6.6,67,69
2,Iron Man 2,2010,Marvel Studios,Jon Favreau,124,One,828995793,170992360,6.9,72,71
3,Thor,2011,Marvel Studios,Kenneth Brangh,115,One,596646818,87271973,7.0,77,76
4,Captain America: The First Avenger,2011,Marvel Studios,Joe Johnston,124,One,492068074,86389190,6.9,80,75
5,The Avengers,2012,Marvel Studios,Joss Whedon,143,One,2004272006,274413265,8.0,91,91
6,Iron Man 3,2013,Marvel Studios,Shane Black,130,Two,1574179644,225552578,7.1,79,78
7,Thor: The Dark World,2013,Marvel Studios,Alan Taylor,112,Two,834833354,111040226,6.8,67,75
8,Captain America: The Winter Soldier,2014,Marvel Studios,Anthony and Joe Russo,132,Two,920765217,122472432,7.7,90,92
9,Guardians of The Galaxy,2014,Marvel Studios,James Gunn,121,Two,993337378,121539238,8.0,92,92
10,Avengers: Age of Ultron,2015,Marvel Studios,Joss Whedon,141,Two,1742904818,238918713,7.3,76,82
11,Ant-Man,2015,Marvel Studios,Peyton Reed,117,Two,648111427,71480993,7.3,83,85
12,Captain America: Civil War,2016,Marvel Studios,Anthony and Joe Russo,147,Three,1402254629,218073428,7.8,90,89
13,Doctor Strange,2016,Marvel Studios,Scott Derrickson,115,Three,823020316,103504731,7.5,89,86
14,Guardians of the Galaxy Vol. 2,2017,Marvel Studios,James Gunn,136,Three,1020233676,171990119,7.6,85,87
15,Spider-Man: Homecoming,2017,Marvel Studios,Jon Watts,133,Three,1031014121,137380112,7.4,92,87
16,Thor: Ragnarok,2017,Marvel Studios,Taika Waititi,130,Three,998206128,144064999,7.9,93,87
17,Black Panther,2018,Marvel Studios,Ryan Coogler,134,Three,1544817247,233490845,7.3,96,79
18,Avengers Infinity War,2018,Marvel Studios,Anthony and Joe Russo,149,Three,2367643044,297866285,8.4,85,92
19,Ant-Man and the Wasp,2018,Marvel Studios,Peyton Reed,118,Three,720275869,87629254,7.0,87,80
20,Captain Marvel,2019,Marvel Studios,Anna Boden & Ryan Fleck,123,Three,1298519243,176381435,6.8,79,45
21,Avengers: Endgame,2019,Marvel Studios,Anthony and Joe Russo,181,Three,3206031270,410526314,8.4,94,90
22,Spider-Man: Far From Home,2019,Marvel Studios,Jon Watts,129,Three,1301429278,106425666,7.4,90,95
23,Black Widow,2021,Marvel Studios,Cate Shortland,134,Four,384498021,81370891,6.7,79,91
24,Shang-Chi and the Legend of the Ten Rings,2021,Marvel Studios,Destin Daniel Cretton,132,Four,437627440,76331046,7.4,92,98
25,Eternals,2021,Marvel Studios,Chloe Zhao,156,Four,406748045,72187483,6.3,47,77
26,Spider-Man: No Way Home,2021,Marvel Studios,Jon Watts,148,Four,1924620750,262427180,8.2,93,98
27,Doctor Strange in the Multiverse of Madness,2022,Marvel Studios,Sam Raimi,126,Four,952224986,187420998,6.9,73,85
28,Thor: Love and Thunder,2022,Marvel Studios,Taika Waititi,118,Four,760928081,144165107,6.2,63,76
29,Black Panther: Wakanda Forever,2022,Marvel Studios,Ryan Coogler,161,Four,853985546,181339761,6.7,83,94
30,Ant-Man and the Wasp: Quantumania,2023,Marvel Studios,Peyton Reed,124,Five,463635303,106109650,6.1,46,82
31,Guardians of the Galaxy Vol. 3,2023,Marvel Studios,James Gunn,150,Five,845468744,118414021,7.9,82,94
32,The Marvels,2023,Marvel Studios,Nia DaCosta,105,Five,199706250,46110859,5.7,62,82

In [14]:
mean_ratings=pd.pivot_table(mcu_movies, values=['Imdb rating','Tomatometer','Rotten Tomato (audience)'],index='Phase',
             aggfunc="mean")

In [15]:
mean_ratings

       Imdb rating  Rotten Tomato (audience)  Tomatometer
Phase
Five      6.566667                 86.000000    63.333333
Four      6.914286                 88.428571    75.714286
One       7.216667                 78.833333    80.166667
Three     7.590909                 83.363636    89.090909
Two       7.366667                 84.000000    81.166667

In [16]:
mean_ratings.plot.bar()

In [17]:
print(mean_ratings.columns)

Index(['Imdb rating', 'Rotten Tomato (audience)', 'Tomatometer'], dtype='object')

In [18]:
fig, ax=plt.subplots()
phases=mean_ratings.index
ratings= mean_ratings['Imdb rating']


bar_labels=['five','four', 'one', 'three', 'two']
bar_colors=['tab:red', 'tab:blue', 'tab:green', '#FFD700', 'tab:purple']
ax.bar(phases,ratings, label=bar_labels, color=bar_colors)

ax.set_ylabel('Imdb ratings')
ax.set_title('Ratings per phase')
ax.legend(title= 'phases')
plt.savefig('Bars(phases).png')

In [19]:
#marvel's recent content hasn't been that good

In [20]:
mcu_movies.dtypes

Movie                           object
Release Year                     int64
Ownership                       object
Director                        object
Run Time(minutes)                int64
Phase                           object
Total Box Office(inflation)      int64
Opening weekend                  int64
Imdb rating                    float64
Tomatometer                      int64
Rotten Tomato (audience)         int64
dtype: object

In [21]:
#phase_one
phase_one= mcu_movies.loc[mcu_movies['Phase'] == 'One']

In [22]:
phase_one

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
0,Iron Man,2008,Marvel Studios,Jon Favreau,126,One,858150722,149756442,7.9,94,91
1,The Incredible Hulk,2008,Marvel Studios,Louis Leterrier,112,One,389483666,81268794,6.6,67,69
2,Iron Man 2,2010,Marvel Studios,Jon Favreau,124,One,828995793,170992360,6.9,72,71
3,Thor,2011,Marvel Studios,Kenneth Brangh,115,One,596646818,87271973,7.0,77,76
4,Captain America: The First Avenger,2011,Marvel Studios,Joe Johnston,124,One,492068074,86389190,6.9,80,75
5,The Avengers,2012,Marvel Studios,Joss Whedon,143,One,2004272006,274413265,8.0,91,91

In [23]:
phase_two=mcu_movies.loc[mcu_movies['Phase'] =='Two']

In [24]:
phase_two

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
6,Iron Man 3,2013,Marvel Studios,Shane Black,130,Two,1574179644,225552578,7.1,79,78
7,Thor: The Dark World,2013,Marvel Studios,Alan Taylor,112,Two,834833354,111040226,6.8,67,75
8,Captain America: The Winter Soldier,2014,Marvel Studios,Anthony and Joe Russo,132,Two,920765217,122472432,7.7,90,92
9,Guardians of The Galaxy,2014,Marvel Studios,James Gunn,121,Two,993337378,121539238,8.0,92,92
10,Avengers: Age of Ultron,2015,Marvel Studios,Joss Whedon,141,Two,1742904818,238918713,7.3,76,82
11,Ant-Man,2015,Marvel Studios,Peyton Reed,117,Two,648111427,71480993,7.3,83,85

In [25]:
phase_three= mcu_movies.loc[mcu_movies['Phase'] == 'Three']

In [26]:
phase_three

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
12,Captain America: Civil War,2016,Marvel Studios,Anthony and Joe Russo,147,Three,1402254629,218073428,7.8,90,89
13,Doctor Strange,2016,Marvel Studios,Scott Derrickson,115,Three,823020316,103504731,7.5,89,86
14,Guardians of the Galaxy Vol. 2,2017,Marvel Studios,James Gunn,136,Three,1020233676,171990119,7.6,85,87
15,Spider-Man: Homecoming,2017,Marvel Studios,Jon Watts,133,Three,1031014121,137380112,7.4,92,87
16,Thor: Ragnarok,2017,Marvel Studios,Taika Waititi,130,Three,998206128,144064999,7.9,93,87
17,Black Panther,2018,Marvel Studios,Ryan Coogler,134,Three,1544817247,233490845,7.3,96,79
18,Avengers Infinity War,2018,Marvel Studios,Anthony and Joe Russo,149,Three,2367643044,297866285,8.4,85,92
19,Ant-Man and the Wasp,2018,Marvel Studios,Peyton Reed,118,Three,720275869,87629254,7.0,87,80
20,Captain Marvel,2019,Marvel Studios,Anna Boden & Ryan Fleck,123,Three,1298519243,176381435,6.8,79,45
21,Avengers: Endgame,2019,Marvel Studios,Anthony and Joe Russo,181,Three,3206031270,410526314,8.4,94,90
22,Spider-Man: Far From Home,2019,Marvel Studios,Jon Watts,129,Three,1301429278,106425666,7.4,90,95

In [27]:
len(phase_three)

11

In [28]:
phase_four=mcu_movies.loc[mcu_movies['Phase'] =='Four']

In [29]:
phase_four

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
23,Black Widow,2021,Marvel Studios,Cate Shortland,134,Four,384498021,81370891,6.7,79,91
24,Shang-Chi and the Legend of the Ten Rings,2021,Marvel Studios,Destin Daniel Cretton,132,Four,437627440,76331046,7.4,92,98
25,Eternals,2021,Marvel Studios,Chloe Zhao,156,Four,406748045,72187483,6.3,47,77
26,Spider-Man: No Way Home,2021,Marvel Studios,Jon Watts,148,Four,1924620750,262427180,8.2,93,98
27,Doctor Strange in the Multiverse of Madness,2022,Marvel Studios,Sam Raimi,126,Four,952224986,187420998,6.9,73,85
28,Thor: Love and Thunder,2022,Marvel Studios,Taika Waititi,118,Four,760928081,144165107,6.2,63,76
29,Black Panther: Wakanda Forever,2022,Marvel Studios,Ryan Coogler,161,Four,853985546,181339761,6.7,83,94

In [30]:
phase_five=mcu_movies.loc[mcu_movies['Phase'] =='Five']

In [31]:
phase_five

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
30,Ant-Man and the Wasp: Quantumania,2023,Marvel Studios,Peyton Reed,124,Five,463635303,106109650,6.1,46,82
31,Guardians of the Galaxy Vol. 3,2023,Marvel Studios,James Gunn,150,Five,845468744,118414021,7.9,82,94
32,The Marvels,2023,Marvel Studios,Nia DaCosta,105,Five,199706250,46110859,5.7,62,82

In [32]:
#Phase one

In [33]:
mcu_movies.columns

Index(['Movie', 'Release Year', 'Ownership', 'Director', 'Run Time(minutes)',
       'Phase', 'Total Box Office(inflation)', 'Opening weekend',
       'Imdb rating', 'Tomatometer', 'Rotten Tomato (audience)'],
      dtype='object')

In [33]:
phase_3=phase_five['Total Box Office(inflation)'].sum()

In [34]:
phase_3

1508810297

In [ ]:
def box_office_totals(mcu_movies):
    phase_count = int(input("How many phases do you want to enter? "))
    results = []

    for i in range(phase_count):
        user_input = input(f"Enter Marvel Phase: ")
        phase = user_input.capitalize()

        phase_movies = mcu_movies[mcu_movies['Phase'] == phase]

        if phase_movies.empty:
            print(f"No data found for Phase {phase}.")
            results.append((phase, 0))
        else:
            total_box_office = phase_movies['Total Box Office(inflation)'].sum()
            results.append((phase, total_box_office))

    return results

# Now call the function and print the results
totals = box_office_totals(mcu_movies)

for phase, boxoffice in totals:
    print(f"Total box office for Phase {phase}: ${boxoffice:,.2f}")

In [ ]:
results = box_office_totals(mcu_movies)
fig, ax=plt.subplots()
phases=[phase for phase,total in results]
y_pos=np.arange(len(phases))
box_office_totals=[total for phase,total in results]
bar_colors=['tab:red','tab:blue','tab:green','#FFD700','tab:purple']
ax.barh(y_pos, box_office_totals, align='center',color=bar_colors[:len(phases)])
ax.set_yticks(y_pos, labels=phases)
ax.invert_yaxis()
ax.set_xlabel('Box office totals/phase')
ax.set_title('Box ofice total for each phase')
plt.savefig('phases.png')

In [34]:
mcu.dtypes

Movie                                  object
Release Date                           object
Release Month                          object
Release Day                             int64
Release Year                            int64
Ownership                              object
Domestic Box Office                     int64
Inflation Adjusted Domestic             int64
International Box Office                int64
Inflation Adjusted International        int64
Worldwide Box Office                    int64
Inflation Adjusted Worldwide            int64
Opening Weekend                         int64
Inflation Adjusted Opening Weekend      int64
Budget                                  int64
Inflation Adjusted Budget               int64
IMDb Score                            float64
Meta Score                              int64
Tomatometer                             int64
Rotten Tomato Audience Score            int64
Run Time In Minutes                     int64
Phase                                  object
Director                               object
dtype: object

In [35]:
revenue_comparison= pd.DataFrame({
    "Movie":mcu['Movie'],
    "Phase": mcu['Phase'],
    "Release year":mcu['Release Year'],
    "Inflation Adjusted Worldwide" : mcu['Inflation Adjusted Worldwide'],
    "Inflation Adjusted Budget": mcu['Inflation Adjusted Budget']
})

In [36]:
revenue_comparison

,Movie,Phase,Release year,Inflation Adjusted Worldwide,Inflation Adjusted Budget
0,Iron Man,One,2008,858150722,272767935
1,The Incredible Hulk,One,2008,389483666,201653899
2,Iron Man 2,One,2010,828995793,226882130
3,Thor,One,2011,596646818,199180327
4,Captain America: The First Avenger,One,2011,492068074,185901643
...,...,...,...,...,...
63,Blade II,NaN,2002,279722109,97869190
64,Blade: Trinity,NaN,2004,222156650,109934026
65,Morbius,NaN,2022,162759437,75000000
66,Hulk,NaN,2003,427891136,239238803
67,Madame Web,NaN,2024,97697905,80000000

In [37]:
mcu_revenue=revenue_comparison.loc[revenue_comparison['Phase'].notna()]

In [38]:
mcu_revenue

,Movie,Phase,Release year,Inflation Adjusted Worldwide,Inflation Adjusted Budget
0,Iron Man,One,2008,858150722,272767935
1,The Incredible Hulk,One,2008,389483666,201653899
2,Iron Man 2,One,2010,828995793,226882130
3,Thor,One,2011,596646818,199180327
4,Captain America: The First Avenger,One,2011,492068074,185901643
5,The Avengers,One,2012,2004272006,297644471
6,Iron Man 3,Two,2013,1574179644,259040588
7,Thor: The Dark World,Two,2013,834833354,194267009
8,Captain America: The Winter Soldier,Two,2014,920765217,219106485
9,Guardians of The Galaxy,Two,2014,993337378,219057220
10,Avengers: Age of Ultron,Two,2015,1742904818,455925262
11,Ant-Man,Two,2015,648111427,162384338
12,Captain America: Civil War,Three,2016,1402254629,304335258
13,Doctor Strange,Three,2016,823020316,200783208
14,Guardians of the Galaxy Vol. 2,Three,2017,1020233676,234782604
15,Spider-Man: Homecoming,Three,2017,1031014121,205434782
16,Thor: Ragnarok,Three,2017,998206128,211264834
17,Black Panther,Three,2018,1544817247,231174532
18,Avengers Infinity War,Three,2018,2367643044,346761799
19,Ant-Man and the Wasp,Three,2018,720275869,150263444
20,Captain Marvel,Three,2019,1298519243,201173581
21,Avengers: Endgame,Three,2019,3206031270,459825329
22,Spider-Man: Far From Home,Three,2019,1301429278,183930131
23,Black Widow,Four,2021,384498021,202500000
24,Shang-Chi and the Legend of the Ten Rings,Four,2021,437627440,151874999
25,Eternals,Four,2021,406748045,202497331
26,Spider-Man: No Way Home,Four,2021,1924620750,201759532
27,Doctor Strange in the Multiverse of Madness,Four,2022,952224986,200000000
28,Thor: Love and Thunder,Four,2022,760928081,250000000
29,Black Panther: Wakanda Forever,Four,2022,853985546,250000000
30,Ant-Man and the Wasp: Quantumania,Five,2023,463635303,200000000
31,Guardians of the Galaxy Vol. 3,Five,2023,845468744,250000000
32,The Marvels,Five,2023,199706250,274800000

In [39]:
total_revenue= pd.pivot_table(mcu_revenue, values=['Inflation Adjusted Worldwide','Inflation Adjusted Budget'], index='Phase',
                             aggfunc="sum")

In [40]:
total_revenue

       Inflation Adjusted Budget  Inflation Adjusted Worldwide
Phase
Five                   724800000                    1508810297
Four                  1458631862                    5720632869
One                   1384030405                    5169617079
Three                 2729729502                   15713444821
Two                   1509780902                    6714131838

In [41]:
total_revenue2=pd.melt(frame=total_revenue.reset_index(), id_vars='Phase',
                       value_vars=['Inflation Adjusted Budget', 'Inflation Adjusted Worldwide'],
                       var_name='Type', value_name='amount')

In [42]:
total_revenue2 = total_revenue2.drop_duplicates()

In [43]:
total_revenue2['Type'] = total_revenue2['Type'].str.strip()

In [73]:
# Reset and verify phase values
print(total_revenue.index)  # should show 'Phase 1', 'Phase 2', etc.
print(total_revenue.columns)  # should include 'budget' and 'worldwide_total'

Index(['Five', 'Four', 'One', 'Three', 'Two'], dtype='object', name='Phase')
Index(['Inflation Adjusted Budget', 'Inflation Adjusted Worldwide'], dtype='object')

In [74]:
plt.figure(figsize=(10,6))
ax=sns.barplot(x='amount', y='Phase', hue='Type', data=total_revenue2)
plt.ylabel('Phase')
plt.title('Budget vs Worldwide Totals per Phase')
handles,labels=ax.get_legend_handles_labels()
custom_labels=['Budget','Worldwide Total']
ax.legend(handles[:2],custom_labels,title='Type')
plt.tight_layout()
plt.savefig('Comparison.png')

In [44]:
non_mcu_movies=mcu_data.loc[mcu_data['Ownership'] != 'Marvel Studios']

In [45]:
non_mcu_movies

,Movie,Release Year,Ownership,Director,Run Time(minutes),Phase,Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
33,Spider-Man,2002,Sony Pictures,Sam Raimi,121,NaN,1489254408,208142606,7.4,90,67
34,Spider-Man 2,2004,Sony Pictures,Sam Raimi,127,NaN,1347530632,149482297,7.5,93,82
35,Spider-Man 3,2007,Sony Pictures,Sam Raimi,139,NaN,1369604387,231287341,6.3,63,51
36,The Amazing Spider-Man,2012,Sony Pictures,Marc Webb,136,NaN,1002585993,82023789,6.9,71,77
37,The Amazing Spider-Man 2,2014,Sony Pictures,Marc Webb,142,NaN,913798188,118070472,6.6,51,64
38,Venom,2018,Sony Pictures,Ruben Fleischer,112,NaN,989518574,92765236,6.6,30,80
39,Venom: Let There be Carnage,2021,Sony Pictures,Andy Serkis,97,NaN,507788633,91153666,5.9,57,84
40,Ghost Rider,2007,Sony Pictures,Mark Steven Johnson,110,NaN,351324848,69468666,5.3,27,48
41,Ghost Rider: Spirit of Vengeance,2012,Sony Pictures,"Mark Neveldine, Brian Taylor",96,NaN,197394298,29255584,4.3,19,31
42,X-Men,2000,20th Century Fox,Brian Singer,104,NaN,579975125,106416440,7.3,82,83
43,X2,2003,20th Century Fox,Brian Singer,134,NaN,709593868,149408529,7.4,85,85
44,X-Men: The Last Stand,2006,20th Century Fox,Brett Ratner,104,NaN,738323311,165185418,6.6,57,61
45,X-Men Origins: Wolverine,2009,20th Century Fox,Gavin Hood,107,NaN,526255368,119421436,6.5,38,58
46,The Wolverine,2013,20th Century Fox,James Mangold,126,NaN,539396116,68793085,6.7,71,69
47,Logan,2017,20th Century Fox,James Mangold,137,NaN,721020107,103787901,8.1,93,90
48,X-Men: First Class,2011,20th Century Fox,Matthew Vaughn,131,NaN,471935626,73167705,7.7,86,87
49,X-Men: Days of Future Past,2014,20th Century Fox,Brian Singer,132,NaN,963891656,117059133,7.9,90,91
50,X-Men: Apocalypse,2016,20th Century Fox,Brian Singer,144,NaN,660453185,80063983,6.9,47,65
51,Dark Phoenix,2019,20th Century Fox,Simon Kinberg,113,NaN,283202845,37738264,5.7,22,64
52,Deadpool,2016,20th Century Fox,Tim Miller,108,NaN,951897008,161218120,8.0,85,90
53,Deadpool 2,2018,20th Century Fox,David Leitch,119,NaN,908933565,145070095,7.6,84,85
54,The New Mutants,2020,20th Century Fox,Josh Boone,94,NaN,49917613,7874577,5.3,36,56
55,Fantastic Four (2005),2005,20th Century Fox,Tim Story,106,NaN,547252377,92094792,5.7,28,45
56,Fantastic Four: Rise of the Silver Surfer,2007,20th Century Fox,Tim Story,92,NaN,443056925,88849452,5.6,38,51
57,Fantastic Four (2015),2015,20th Century Fox,Josh Trank,100,NaN,209662157,32084320,4.3,9,18
58,Elektra,2005,20th Century Fox,Rob Bowman,97,NaN,93348399,21035013,4.7,11,29
59,Daredevil,2003,20th Century Fox,Mark Steven Johnson,103,NaN,319187372,70392817,5.3,43,35
60,The Punisher,2004,Lionsgate Films,Jonathan Hensleigh,124,NaN,92470302,23458543,6.4,29,63
61,Punisher: Warzone,2008,Lionsgate Films,Lexi Alexander,103,NaN,14896773,6264398,5.9,29,42
62,Blade,1998,New Line Cinema,Stephen Norrington,120,NaN,294655175,38334263,7.1,58,78
63,Blade II,2002,New Line Cinema,Guillermo del Toro,117,NaN,279722109,58953529,6.7,57,68
64,Blade: Trinity,2004,New Line Cinema,David S. Goyer,113,NaN,222156650,27164311,5.8,24,58
65,Morbius,2022,Sony Pictures,Daniel Espinosa,104,NaN,162759437,39005895,5.2,15,71
66,Hulk,2003,Universal Pictures,Ang Lee,138,NaN,427891136,108492911,5.6,63,29
67,Madame Web,2024,Sony Pictures,S.J. Clarkson,116,NaN,97697905,15335860,3.8,12,57

In [46]:
fox_sony_movies=non_mcu_movies.drop(['Phase'],axis=1)

In [47]:
fox_sony_movies

,Movie,Release Year,Ownership,Director,Run Time(minutes),Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
33,Spider-Man,2002,Sony Pictures,Sam Raimi,121,1489254408,208142606,7.4,90,67
34,Spider-Man 2,2004,Sony Pictures,Sam Raimi,127,1347530632,149482297,7.5,93,82
35,Spider-Man 3,2007,Sony Pictures,Sam Raimi,139,1369604387,231287341,6.3,63,51
36,The Amazing Spider-Man,2012,Sony Pictures,Marc Webb,136,1002585993,82023789,6.9,71,77
37,The Amazing Spider-Man 2,2014,Sony Pictures,Marc Webb,142,913798188,118070472,6.6,51,64
38,Venom,2018,Sony Pictures,Ruben Fleischer,112,989518574,92765236,6.6,30,80
39,Venom: Let There be Carnage,2021,Sony Pictures,Andy Serkis,97,507788633,91153666,5.9,57,84
40,Ghost Rider,2007,Sony Pictures,Mark Steven Johnson,110,351324848,69468666,5.3,27,48
41,Ghost Rider: Spirit of Vengeance,2012,Sony Pictures,"Mark Neveldine, Brian Taylor",96,197394298,29255584,4.3,19,31
42,X-Men,2000,20th Century Fox,Brian Singer,104,579975125,106416440,7.3,82,83
43,X2,2003,20th Century Fox,Brian Singer,134,709593868,149408529,7.4,85,85
44,X-Men: The Last Stand,2006,20th Century Fox,Brett Ratner,104,738323311,165185418,6.6,57,61
45,X-Men Origins: Wolverine,2009,20th Century Fox,Gavin Hood,107,526255368,119421436,6.5,38,58
46,The Wolverine,2013,20th Century Fox,James Mangold,126,539396116,68793085,6.7,71,69
47,Logan,2017,20th Century Fox,James Mangold,137,721020107,103787901,8.1,93,90
48,X-Men: First Class,2011,20th Century Fox,Matthew Vaughn,131,471935626,73167705,7.7,86,87
49,X-Men: Days of Future Past,2014,20th Century Fox,Brian Singer,132,963891656,117059133,7.9,90,91
50,X-Men: Apocalypse,2016,20th Century Fox,Brian Singer,144,660453185,80063983,6.9,47,65
51,Dark Phoenix,2019,20th Century Fox,Simon Kinberg,113,283202845,37738264,5.7,22,64
52,Deadpool,2016,20th Century Fox,Tim Miller,108,951897008,161218120,8.0,85,90
53,Deadpool 2,2018,20th Century Fox,David Leitch,119,908933565,145070095,7.6,84,85
54,The New Mutants,2020,20th Century Fox,Josh Boone,94,49917613,7874577,5.3,36,56
55,Fantastic Four (2005),2005,20th Century Fox,Tim Story,106,547252377,92094792,5.7,28,45
56,Fantastic Four: Rise of the Silver Surfer,2007,20th Century Fox,Tim Story,92,443056925,88849452,5.6,38,51
57,Fantastic Four (2015),2015,20th Century Fox,Josh Trank,100,209662157,32084320,4.3,9,18
58,Elektra,2005,20th Century Fox,Rob Bowman,97,93348399,21035013,4.7,11,29
59,Daredevil,2003,20th Century Fox,Mark Steven Johnson,103,319187372,70392817,5.3,43,35
60,The Punisher,2004,Lionsgate Films,Jonathan Hensleigh,124,92470302,23458543,6.4,29,63
61,Punisher: Warzone,2008,Lionsgate Films,Lexi Alexander,103,14896773,6264398,5.9,29,42
62,Blade,1998,New Line Cinema,Stephen Norrington,120,294655175,38334263,7.1,58,78
63,Blade II,2002,New Line Cinema,Guillermo del Toro,117,279722109,58953529,6.7,57,68
64,Blade: Trinity,2004,New Line Cinema,David S. Goyer,113,222156650,27164311,5.8,24,58
65,Morbius,2022,Sony Pictures,Daniel Espinosa,104,162759437,39005895,5.2,15,71
66,Hulk,2003,Universal Pictures,Ang Lee,138,427891136,108492911,5.6,63,29
67,Madame Web,2024,Sony Pictures,S.J. Clarkson,116,97697905,15335860,3.8,12,57

In [48]:
mutant_saga=fox_sony_movies.loc[42:54]

In [49]:
mutant_saga

,Movie,Release Year,Ownership,Director,Run Time(minutes),Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
42,X-Men,2000,20th Century Fox,Brian Singer,104,579975125,106416440,7.3,82,83
43,X2,2003,20th Century Fox,Brian Singer,134,709593868,149408529,7.4,85,85
44,X-Men: The Last Stand,2006,20th Century Fox,Brett Ratner,104,738323311,165185418,6.6,57,61
45,X-Men Origins: Wolverine,2009,20th Century Fox,Gavin Hood,107,526255368,119421436,6.5,38,58
46,The Wolverine,2013,20th Century Fox,James Mangold,126,539396116,68793085,6.7,71,69
47,Logan,2017,20th Century Fox,James Mangold,137,721020107,103787901,8.1,93,90
48,X-Men: First Class,2011,20th Century Fox,Matthew Vaughn,131,471935626,73167705,7.7,86,87
49,X-Men: Days of Future Past,2014,20th Century Fox,Brian Singer,132,963891656,117059133,7.9,90,91
50,X-Men: Apocalypse,2016,20th Century Fox,Brian Singer,144,660453185,80063983,6.9,47,65
51,Dark Phoenix,2019,20th Century Fox,Simon Kinberg,113,283202845,37738264,5.7,22,64
52,Deadpool,2016,20th Century Fox,Tim Miller,108,951897008,161218120,8.0,85,90
53,Deadpool 2,2018,20th Century Fox,David Leitch,119,908933565,145070095,7.6,84,85
54,The New Mutants,2020,20th Century Fox,Josh Boone,94,49917613,7874577,5.3,36,56

In [50]:
spiderman_universe=fox_sony_movies.loc[33:39]

In [51]:
spiderman_universe

,Movie,Release Year,Ownership,Director,Run Time(minutes),Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
33,Spider-Man,2002,Sony Pictures,Sam Raimi,121,1489254408,208142606,7.4,90,67
34,Spider-Man 2,2004,Sony Pictures,Sam Raimi,127,1347530632,149482297,7.5,93,82
35,Spider-Man 3,2007,Sony Pictures,Sam Raimi,139,1369604387,231287341,6.3,63,51
36,The Amazing Spider-Man,2012,Sony Pictures,Marc Webb,136,1002585993,82023789,6.9,71,77
37,The Amazing Spider-Man 2,2014,Sony Pictures,Marc Webb,142,913798188,118070472,6.6,51,64
38,Venom,2018,Sony Pictures,Ruben Fleischer,112,989518574,92765236,6.6,30,80
39,Venom: Let There be Carnage,2021,Sony Pictures,Andy Serkis,97,507788633,91153666,5.9,57,84

In [52]:
others=fox_sony_movies.loc[55:67]

In [53]:
others

,Movie,Release Year,Ownership,Director,Run Time(minutes),Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience)
55,Fantastic Four (2005),2005,20th Century Fox,Tim Story,106,547252377,92094792,5.7,28,45
56,Fantastic Four: Rise of the Silver Surfer,2007,20th Century Fox,Tim Story,92,443056925,88849452,5.6,38,51
57,Fantastic Four (2015),2015,20th Century Fox,Josh Trank,100,209662157,32084320,4.3,9,18
58,Elektra,2005,20th Century Fox,Rob Bowman,97,93348399,21035013,4.7,11,29
59,Daredevil,2003,20th Century Fox,Mark Steven Johnson,103,319187372,70392817,5.3,43,35
60,The Punisher,2004,Lionsgate Films,Jonathan Hensleigh,124,92470302,23458543,6.4,29,63
61,Punisher: Warzone,2008,Lionsgate Films,Lexi Alexander,103,14896773,6264398,5.9,29,42
62,Blade,1998,New Line Cinema,Stephen Norrington,120,294655175,38334263,7.1,58,78
63,Blade II,2002,New Line Cinema,Guillermo del Toro,117,279722109,58953529,6.7,57,68
64,Blade: Trinity,2004,New Line Cinema,David S. Goyer,113,222156650,27164311,5.8,24,58
65,Morbius,2022,Sony Pictures,Daniel Espinosa,104,162759437,39005895,5.2,15,71
66,Hulk,2003,Universal Pictures,Ang Lee,138,427891136,108492911,5.6,63,29
67,Madame Web,2024,Sony Pictures,S.J. Clarkson,116,97697905,15335860,3.8,12,57

In [54]:
mutant_saga['Universe']='Mutant'
spiderman_universe['Universe']= 'Spidey'
others['Universe']= 'Other_heros'

/data/user/0/ru.iiec.pydroid3/cache/ipykernel_9595/357365197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mutant_saga['Universe']='Mutant'
/data/user/0/ru.iiec.pydroid3/cache/ipykernel_9595/357365197.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spiderman_universe['Universe']= 'Spidey'
/data/user/0/ru.iiec.pydroid3/cache/ipykernel_9595/357365197.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  others['Universe']= 'Other_heros'

In [55]:
combined=pd.concat([mutant_saga,spiderman_universe,others])

In [56]:
combined

,Movie,Release Year,Ownership,Director,Run Time(minutes),Total Box Office(inflation),Opening weekend,Imdb rating,Tomatometer,Rotten Tomato (audience),Universe
42,X-Men,2000,20th Century Fox,Brian Singer,104,579975125,106416440,7.3,82,83,Mutant
43,X2,2003,20th Century Fox,Brian Singer,134,709593868,149408529,7.4,85,85,Mutant
44,X-Men: The Last Stand,2006,20th Century Fox,Brett Ratner,104,738323311,165185418,6.6,57,61,Mutant
45,X-Men Origins: Wolverine,2009,20th Century Fox,Gavin Hood,107,526255368,119421436,6.5,38,58,Mutant
46,The Wolverine,2013,20th Century Fox,James Mangold,126,539396116,68793085,6.7,71,69,Mutant
47,Logan,2017,20th Century Fox,James Mangold,137,721020107,103787901,8.1,93,90,Mutant
48,X-Men: First Class,2011,20th Century Fox,Matthew Vaughn,131,471935626,73167705,7.7,86,87,Mutant
49,X-Men: Days of Future Past,2014,20th Century Fox,Brian Singer,132,963891656,117059133,7.9,90,91,Mutant
50,X-Men: Apocalypse,2016,20th Century Fox,Brian Singer,144,660453185,80063983,6.9,47,65,Mutant
51,Dark Phoenix,2019,20th Century Fox,Simon Kinberg,113,283202845,37738264,5.7,22,64,Mutant
52,Deadpool,2016,20th Century Fox,Tim Miller,108,951897008,161218120,8.0,85,90,Mutant
53,Deadpool 2,2018,20th Century Fox,David Leitch,119,908933565,145070095,7.6,84,85,Mutant
54,The New Mutants,2020,20th Century Fox,Josh Boone,94,49917613,7874577,5.3,36,56,Mutant
33,Spider-Man,2002,Sony Pictures,Sam Raimi,121,1489254408,208142606,7.4,90,67,Spidey
34,Spider-Man 2,2004,Sony Pictures,Sam Raimi,127,1347530632,149482297,7.5,93,82,Spidey
35,Spider-Man 3,2007,Sony Pictures,Sam Raimi,139,1369604387,231287341,6.3,63,51,Spidey
36,The Amazing Spider-Man,2012,Sony Pictures,Marc Webb,136,1002585993,82023789,6.9,71,77,Spidey
37,The Amazing Spider-Man 2,2014,Sony Pictures,Marc Webb,142,913798188,118070472,6.6,51,64,Spidey
38,Venom,2018,Sony Pictures,Ruben Fleischer,112,989518574,92765236,6.6,30,80,Spidey
39,Venom: Let There be Carnage,2021,Sony Pictures,Andy Serkis,97,507788633,91153666,5.9,57,84,Spidey
55,Fantastic Four (2005),2005,20th Century Fox,Tim Story,106,547252377,92094792,5.7,28,45,Other_heros
56,Fantastic Four: Rise of the Silver Surfer,2007,20th Century Fox,Tim Story,92,443056925,88849452,5.6,38,51,Other_heros
57,Fantastic Four (2015),2015,20th Century Fox,Josh Trank,100,209662157,32084320,4.3,9,18,Other_heros
58,Elektra,2005,20th Century Fox,Rob Bowman,97,93348399,21035013,4.7,11,29,Other_heros
59,Daredevil,2003,20th Century Fox,Mark Steven Johnson,103,319187372,70392817,5.3,43,35,Other_heros
60,The Punisher,2004,Lionsgate Films,Jonathan Hensleigh,124,92470302,23458543,6.4,29,63,Other_heros
61,Punisher: Warzone,2008,Lionsgate Films,Lexi Alexander,103,14896773,6264398,5.9,29,42,Other_heros
62,Blade,1998,New Line Cinema,Stephen Norrington,120,294655175,38334263,7.1,58,78,Other_heros
63,Blade II,2002,New Line Cinema,Guillermo del Toro,117,279722109,58953529,6.7,57,68,Other_heros
64,Blade: Trinity,2004,New Line Cinema,David S. Goyer,113,222156650,27164311,5.8,24,58,Other_heros
65,Morbius,2022,Sony Pictures,Daniel Espinosa,104,162759437,39005895,5.2,15,71,Other_heros
66,Hulk,2003,Universal Pictures,Ang Lee,138,427891136,108492911,5.6,63,29,Other_heros
67,Madame Web,2024,Sony Pictures,S.J. Clarkson,116,97697905,15335860,3.8,12,57,Other_heros

In [57]:
aggfuncs = {'Total Box Office(inflation)': 'sum'}
mean_cols = ['Imdb rating', 'Tomatometer', 'Rotten Tomato (audience)', 'Run Time(minutes)']
aggfuncs.update({col: 'mean' for col in mean_cols})

universe_comparison = combined.pivot_table(
    index='Universe',
    values=list(aggfuncs.keys()),
    aggfunc=aggfuncs,
    fill_value=0
)

In [58]:
universe_comparison.sort_values(by=['Imdb rating'],ascending=False)

,Imdb rating,Rotten Tomato (audience),Run Time(minutes),Tomatometer,Total Box Office(inflation)
Universe,,,,,
Mutant,7.053846,75.692308,119.461538,67.384615,8104795393
Spidey,6.742857,72.142857,124.857143,65.000000,7620080815
Other_heros,5.546154,49.538462,110.230769,32.000000,3204756717

In [ ]:
#Is there a relationship between release month and revenue generated?
#Relationship btwn run time and revenue generated
#Audience and critics score
#Comparison btw the mcu and other projects
# Revenue and runtime 
# How often are movies released(month)
#T-test for comparing average ratings for mcu and other projects

In [99]:
mcu.dtypes

Movie                                  object
Release Date                           object
Release Month                          object
Release Day                             int64
Release Year                            int64
Ownership                              object
Domestic Box Office                     int64
Inflation Adjusted Domestic             int64
International Box Office                int64
Inflation Adjusted International        int64
Worldwide Box Office                    int64
Inflation Adjusted Worldwide            int64
Opening Weekend                         int64
Inflation Adjusted Opening Weekend      int64
Budget                                  int64
Inflation Adjusted Budget               int64
IMDb Score                            float64
Meta Score                              int64
Tomatometer                             int64
Rotten Tomato Audience Score            int64
Run Time In Minutes                     int64
Phase                                  object
Director                               object
dtype: object

In [4]:
#line chart to show frequency of release months 
release_months= pd.DataFrame({
    "Movie":mcu['Movie'],
    "Release Month":mcu['Release Month'],
})

In [5]:
release_months=release_months.loc[0:32]

In [6]:
release_months

                                          Movie Release Month
0                                      Iron Man           May
1                           The Incredible Hulk          June
2                                    Iron Man 2           May
3                                          Thor           May
4            Captain America: The First Avenger          July
5                                  The Avengers           May
6                                    Iron Man 3           May
7                          Thor: The Dark World      November
8           Captain America: The Winter Soldier         April
9                       Guardians of The Galaxy        August
10                      Avengers: Age of Ultron           May
11                                      Ant-Man          July
12                   Captain America: Civil War           May
13                               Doctor Strange      November
14               Guardians of the Galaxy Vol. 2           May
15                       Spider-Man: Homecoming          July
16                               Thor: Ragnarok      November
17                                Black Panther      February
18                        Avengers Infinity War         April
19                         Ant-Man and the Wasp          July
20                               Captain Marvel         March
21                            Avengers: Endgame         April
22                    Spider-Man: Far From Home          July
23                                  Black Widow          July
24    Shang-Chi and the Legend of the Ten Rings     September
25                                     Eternals      November
26                      Spider-Man: No Way Home      December
27  Doctor Strange in the Multiverse of Madness           May
28                       Thor: Love and Thunder          July
29               Black Panther: Wakanda Forever      November
30            Ant-Man and the Wasp: Quantumania      February
31               Guardians of the Galaxy Vol. 3           May
32                                  The Marvels      November

In [7]:
months = pd.to_datetime(release_months['Release Month'], format='%B', errors='coerce')
release_months['Month_Name'] = months.dt.strftime('%B')
frequency=release_months.drop(['Release Month'], axis=1)
grouped_data = frequency.groupby('Month_Name')

In [8]:
grouped_data.count()

            Movie
Month_Name
April           3
August          1
December        1
February        2
July            7
June            1
March           1
May            10
November        6
September       1

In [9]:
grouped_data = frequency.groupby(['Month_Name'])['Movie'].count().reset_index()

In [89]:
grouped_data.sort_values('Month_Name')

  Month_Name  Movie
0      April      3
1     August      1
2   December      1
3   February      2
4       July      7
5       June      1
6      March      1
7        May     10
8   November      6
9  September      1

In [13]:
# Convert month names to datetime (using a dummy day/year)
grouped_data["Month_dt"] = pd.to_datetime(grouped_data["Month_Name"], format="%b")
grouped_Data = grouped_data.sort_values("Month_dt")

ValueError: unconverted data remains when parsing with format "%b": "il", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [14]:
grouped_data.dtypes

Month_Name            object
Movie                  int64
Month_dt      datetime64[ns]
dtype: object

In [12]:
grouped_Data

  Month_Name  Movie   Month_dt
3   February      2 1900-02-01
6      March      1 1900-03-01
0      April      3 1900-04-01
7        May     10 1900-05-01
5       June      1 1900-06-01
4       July      7 1900-07-01
1     August      1 1900-08-01
9  September      1 1900-09-01
8   November      6 1900-11-01
2   December      1 1900-12-01

In [87]:
plt.rcParams.update({'figure.autolayout': True})
fig,ax=plt.subplots()
ax.plot(grouped_data['Month_Name'],grouped_data['Movie'], color='red', linewidth=2)
ax.set_xlabel('Month')
ax.set_ylabel('Movies')
ax.set_title('Release frequency per Month')
plt.setp(ax.get_xticklabels(), rotation=45,horizontalalignment='right')

# Add the grid
ax.grid(True)

# Show the plot
fig.savefig('Release_frequency.png')